### ISSUE TITLE
Payoff for insurance bet is incorrect

### ISSUE THREAD

**Issue by txlouder** [1andDone/blackjack#2]
https://github.com/1andDone/blackjack/blob/2ca79d36a83e880bf091ba55a0b2752646ba37c8/gameplay.py#L70

Insurance pays 2:1 on a bet equal to half the initial bet.  Line above should read

                        net_winnings=1.0,

**Comment by 1andDone** [comment]
@txlouder sorry for the slow response - it's been awhile since I checked on this. I just looked into your comment a little and don't think there is an issue. Explanation below:

The `update_results` function in `simulation_stats.py` does this:

```
def update_results(self, count_key, hand_key=1, net_winnings=0, overall_bet=0, increment=1):
        self._results_dict[count_key]['net winnings'] += net_winnings
        self._results_dict[count_key]['overall bet'] += overall_bet
        if hand_key == 1:
            self._results_dict[count_key]['number of rounds'] += increment
        else:
            self._results_dict[count_key]['number of split hands'] += increment
```

For the insurance case, if your initial bet was $1, you would place an insurance bet of $0.50. If you won that bet you would win $1 (which pays 2:1) but your **net** winnings would only be $0.50 (since you bet $0.50 and won $1). Hence, why ```net winnings=0.5```. 

Let me know if that makes sense. I'll have to revamp this code at some point, it can be re-written in a much nicer way.
